// Phase B — authenticated e2e tests requiring real Supabase + persona auth state.
//
// Builds with real env vars (reads from .env.e2e.local). Requires auth state
// files generated by globalSetup (e2e/setup/auth.setup.js), which in turn
// requires test accounts seeded by:
//   npm run test:e2e:local-auth
//
// Run with:
//   npm run test:e2e:auth
//
// Anonymous fixture-based flows live in playwright.config.js.

import { defineConfig, devices } from '@playwright/test'
import { loadEnvFile } from './scripts/load-env-file.js'

loadEnvFile('.env.e2e.local')

const PORT     = 4174
const BASE_URL = `http://localhost:${PORT}`

export default defineConfig({
  testDir: './e2e',
  // CUSTOMISE THIS: list the spec files that require auth state.
  testMatch: /\/(account|admin|gates|nav|journey-.+)\.spec\.js$/,
  workers: 1,           // one worker: all projects share local Supabase DB state
  fullyParallel: false, // tests within each project run serially
  forbidOnly: !!process.env.CI,
  retries: process.env.CI ? 1 : 0,
  reporter: process.env.CI ? 'github' : 'list',
  globalSetup: './e2e/setup/auth.setup.js',

  use: {
    baseURL: BASE_URL,
    trace: 'on-first-retry',
  },

  projects: [
    // CUSTOMISE THIS: add/remove projects to match your persona set.
    // Each project maps to a storageState file generated by auth.setup.js.
    {
      name: 'account',
      use: {
        ...devices['Desktop Chrome'],
        storageState: 'e2e/auth-state/user.json',
      },
      testMatch: /account\.spec\.js$/,
    },
    {
      name: 'admin',
      use: {
        ...devices['Desktop Chrome'],
        storageState: 'e2e/auth-state/admin.json',
      },
      testMatch: /admin\.spec\.js$/,
    },
    {
      name: 'gates',
      use: { ...devices['Desktop Chrome'] },
      testMatch: /gates\.spec\.js$/,
    },
    {
      name: 'nav',
      use: { ...devices['Desktop Chrome'] },
      testMatch: /nav\.spec\.js$/,
    },
  ],

  webServer: {
    command: `npm run build && npm run preview -- --port ${PORT} --strictPort`,
    url: BASE_URL,
    reuseExistingServer: !process.env.CI,
    timeout: 120_000,
  },
})
